### ISSUE TITLE
Fernflower build fails with openjdk 11

### ISSUE THREAD

**Issue by smandon** [ThisIsLibra/AndroidProjectCreator#1]
I tried to install it under linux mint 19.1 which comes with openjdk 11 installed by default.

During the installation it fails to compile fernflower due to the java version check, the error is:

> [+]Starting to build fernflower
Downloading https://services.gradle.org/distributions/gradle-4.0-all.zip
.....................................................................................
Unzipping /home/user/.gradle/wrapper/dists/gradle-4.0-all/ac27o8rbd0ic8ih41or9l32mv/gradle-4.0-all.zip to /home/user/.gradle/wrapper/dists/gradle-4.0-all/ac27o8rbd0ic8ih41or9l32mv
Set executable permissions for: /home/user/.gradle/wrapper/dists/gradle-4.0-all/ac27o8rbd0ic8ih41or9l32mv/gradle-4.0/bin/gradle
FAILURE: Build failed with an exception.
What went wrong:
Could not determine java version from '10.0.2'.

It works with openjdk 8

**Comment by ThisIsLibra** [comment]
As stated on my website (linked in the ReadMe.md of this project), one should have installed Java 8 JRE and JDK, together with Maven. The "JAVA_HOME" variable should point to the Java 8 JDK. This is because multiple projects that are used, depend on Java 8.
