### ISSUE TITLE
Network problems

### ISSUE THREAD

**Issue by Ceson-L** [ThisIsLibra/AndroidProjectCreator#17]
Hello, unfortunately, due to the national and regional network problems, '- install' can't pull the code normally. I hope you can completely package the folder 'Library' required by '- install' into a file, so that we can download it faster. Thank you!

**Comment by ThisIsLibra** [comment]
Hello, this feature exists since the 28th of July 2020, as can be read [here](https://maxkersten.nl/2020/07/28/androidprojectcreator-1-4-stable-release/). Simply use `-compactInstall`, as is also documented in the program's printed help. I will close this issue as its already resolved.
