### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by dpatrongomez** [ThisIsLibra/AndroidProjectCreator#5]
Hi, I get this error when I use the command 
`java -jar ./AndroidProjectCreator.jar -install`

![Captura](https://user-images.githubusercontent.com/26688719/54810702-07ffa080-4c87-11e9-8a75-0c8c755ccf1e.PNG)

Thanks for you work 👍

**Comment by ThisIsLibra** [comment]
Hello dpatrongomez,

Thank you for opening an issue! The "SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"." error message is one that is generated by the "org.eclipse.jgit" dependency. The absence of the given class results in a no-operation (NOP) logger, meaning the output is redirected to the standard output, which is used in AndroidProjectCreator.

It is known (and expected) behaviour and should not cause a problem. If you do run into problems, please re-open this issue!

Thank you for your time!

Kind regards,
Max 'Libra' Kersten
