### ISSUE TITLE
i m not able to run properly androidpoject crestor

### ISSUE THREAD

**Issue by amit343** [ThisIsLibra/AndroidProjectCreator#6]
warn: missing 'PROJECT/library/temp/984733b0-5b5b-445b-a784-949ac2f2ce3c/output.jar', ignored
error: destination 'PROJECT/library/temp/984733b0-5b5b-445b-a784-949ac2f2ce3c/sources' is not a directory

**Comment by ThisIsLibra** [comment]
Hello amit343,

Could you specify what you did before the error occurred? Can you replicate it? Which version of APC are you using? Solemnly based on the provided information, I'm unable to help you out.

Kind regards,
Libra

**Comment by ThisIsLibra** [comment]
Closed due to a lack of information and response. Feel free to open this ticket again when you do add the details.
