### ISSUE TITLE
Error Permission

### ISSUE THREAD

**Issue by dpatrongomez** [ThisIsLibra/AndroidProjectCreator#7]
Hi, I get this error

![image](https://user-images.githubusercontent.com/26688719/55516760-850b1c80-566e-11e9-9dd8-f28fff1a6cd9.png)

**Comment by ThisIsLibra** [comment]
Hello,

Could you specify the version of AndroidProjectCreator and your Java version? Based on that, we can further see what the issue is.

Kind regards,
Max

**Comment by dpatrongomez** [comment]
`java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
`


AndroidProjectCreator-1.2.2-stable-jar-with-dependencies.jar

**Comment by ThisIsLibra** [comment]
Thank you for youranswer, as stated on the [read me](https://maxkersten.nl/projects/androidprojectcreator/) (also linked in ReadMe.md), you need openjdk8 instead of 10, since the tools that APC uses depend on it and crash otherwise.

This should resolve your issue. Let me know if it does!

**Comment by dpatrongomez** [comment]
> Thank you for youranswer, as stated on the [read me](https://maxkersten.nl/projects/androidprojectcreator/) (also linked in ReadMe.md), you need openjdk8 instead of 10, since the tools that APC uses depend on it and crash otherwise.
> 
> This should resolve your issue. Let me know if it does!

same problem with 
`java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)`

**Comment by ThisIsLibra** [comment]
Could you remove your complete installation of APC and download the JAR again? After that, please install the required files again. If you encounter an error in that process, please share the full log here. If you dont, please decompile an APK of your choice and see if the problem still exists. If it does, please share the full log here.

**Comment by dpatrongomez** [comment]
https://del.dog/cuhizuqitu.sql

**Comment by ThisIsLibra** [comment]
Thank you. It seems like APC itself is working correctly, but dex2jar cannot be build from source. The reason for this, according to the given exception, is that "services.gradle.org" is unreachable. Please make sure it is reachable.

I'll try to help you solve the issue, but its not one that is related to APC.
