### ISSUE TITLE
Build faild with jd-core

### ISSUE THREAD

**Issue by naveenkg29** [ThisIsLibra/AndroidProjectCreator#8]
The following tools failed to install correctly:
		JDCMD

[stack-trace.txt](https://github.com/ThisIsLibra/AndroidProjectCreator/files/3333864/stack-trace.txt)

Attached terminal output

**Comment by ThisIsLibra** [comment]
Thank you for the notification, but please fill the template report next time when you report a bug, as it decreases the time that is required for the analysis.

It looks like the required data is not available on the Maven repository. As such, I'll provide a local mirror in the next release of AndroidProjectCreator, which should solve this issue.

**Comment by ThisIsLibra** [comment]
With the release of version [1.3-stable](https://github.com/ThisIsLibra/AndroidProjectCreator/releases/tag/1.3-stable), this issue is resolved. Therefore, the issue can also be closed. 

Thank you for reporting the issue!
