### ISSUE TITLE
Build failed with jadx

### ISSUE THREAD

**Issue by owen800q** [ThisIsLibra/AndroidProjectCreator#9]
When built the decompiled apk, the error message shown
```
/media/Programming/Reverse_engineering/Android/Tools/Decompiler/AndroidProjectCreator/build/didi_src/app/src/main/res/drawable-v21/$avd_show_password__2.xml: Error: '$' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
/media/Programming/Reverse_engineering/Android/Tools/Decompiler/AndroidProjectCreator/build/didi_src/app/src/main/res/assets/crashlytics-build.properties: Error: The file name must end with .xml
/media/Programming/Reverse_engineering/Android/Tools/Decompiler/AndroidProjectCreator/build/didi_src/app/src/main/res/drawable-v24/$ic_launcher_foreground__0.xml: Error: '$' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
```
## Project view
![image](https://user-images.githubusercontent.com/19252045/62990315-1771c700-be7e-11e9-8b16-8ae19c9cd564.png)

**Comment by owen800q** [comment]
After I renamed the file name, two of three errors has gone, but still get this error
```
/res/assets/crashlytics-build.properties: Error: The file name must end with .xml
```

**Comment by owen800q** [comment]
Solved, this is because the assets folder being placed under the res directory
Instead, it should  be src/main/assets not src/main/res/assets

**Comment by ANR2ME** [comment]
@owen800q did you moves the whole assets folder from `src/main/res/` to `src/main/res/` or only those resources that have `$`?

Also did you rename the file by removing the `$` only?

**Comment by ComValer** [comment]
What do you tryin to do with .. Genshin Impact android package?

**Comment by MuppetWizard** [comment]
> Solved, this is because the assets folder being placed under the res directory Instead, it should be src/main/assets not src/main/res/assets

I got this error too , but I don't understand how did you resolved it. can you explain thast in detail?
